name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-orchestration:
    env:
      base_image: "registry.cn-hangzhou.aliyuncs.com/wisecloud-image/wisecloud-alpine:3.18.6"
      builder: "registry.cn-hangzhou.aliyuncs.com/wisecloud-image/golang-builder:1.13.8-alpine"
    runs-on: "ubuntu-latest"
    steps:
    - env:
        platform: "${{ matrix.platform }}"
        template: "registry.cn-hangzhou.aliyuncs.com/wise2c-dev/orchestration:${{ steps.meta.outputs.version }}-ARCH"
      name: "Build the Docker image"
      run: docker-compose up -d
      timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        platform:
        - "linux/amd64"
  manifest-orchestration:
    env:
      platforms: "linux/amd64,linux/arm64"
    needs:
    - "build-orchestration"
    runs-on: "ubuntu-latest"
    steps:
    - env:
        target: "registry.cn-hangzhou.aliyuncs.com/wise2c-dev/orchestration:${{ steps.meta.outputs.version }}"
        template: "registry.cn-hangzhou.aliyuncs.com/wise2c-dev/orchestration:${{ steps.meta.outputs.version }}-ARCH"
      name: "Build the Manifest"
      run: |
        echo "Pushing image"
