name: Build Docker Image

on:
  push:
    branches:
      - main  # 在 main 分支的推送时触发
  pull_request:
    branches:
      - main  # 在对 main 分支的拉取请求时触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker-compose build  # 构建镜像
