name: Build and Push Docker Image

on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches:
      - main  # 在 main 分支的推送时触发
  pull_request:
    branches:
      - main  # 在对 main 分支的拉取请求时触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose  # 安装 Docker Compose

      - name: Build Docker image
        run: |
          docker-compose build  # 构建镜像

      - name: Log in to Docker registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username="${{ secrets.DOCKER_USERNAME }}" --password-stdin crpi-3yj0xy215oa2xdp6.cn-shenzhen.personal.cr.aliyuncs.com

      - name: Tag and Push Docker image
        run: |
          docker tag library/notary_server crpi-3yj0xy215oa2xdp6.cn-shenzhen.personal.cr.aliyuncs.com/jay0001/notary_server:latest  # 替换为你的仓库和标签
          docker push crpi-3yj0xy215oa2xdp6.cn-shenzhen.personal.cr.aliyuncs.com/jay0001/notary_server:latest  # 推送镜像
